import React from 'react';
import {AbsoluteFill,Sequence,interpolate,useCurrentFrame,useVideoConfig} from 'remotion';
import {ThreeCanvas} from '@remotion/three';

const C={bg:'#10141e',blue:'#2457ff',yellow:'#ffd84d',cyan:'#4ce3ff',red:'#ff4f5e',cream:'#f6f3e9',muted:'#9aa7bb'};
const BG=({children,light=false})=><AbsoluteFill style={{background:light?'#f3f0e8':'radial-gradient(circle at 50% 15%,#23365e 0%,#10141e 55%,#070a10 100%)',color:light?'#11151f':C.cream,fontFamily:'Arial,sans-serif',overflow:'hidden'}}>{children}</AbsoluteFill>;
const p01=()=>{const f=useCurrentFrame(),{durationInFrames}=useVideoConfig();return Math.max(0,Math.min(1,f/Math.max(1,durationInFrames-1)));};
const Title=({children,y=150,size=60,color=C.cream})=><div style={{position:'absolute',top:y,left:70,right:70,textAlign:'center',fontSize:size,fontWeight:900,lineHeight:1.02,color}}>{children}</div>;
const Pill=({x,y,w=280,h=115,label,color=C.blue})=><div style={{position:'absolute',left:x,top:y,width:w,height:h,borderRadius:28,background:color,display:'flex',alignItems:'center',justifyContent:'center',fontSize:30,fontWeight:850,textAlign:'center',padding:12}}>{label}</div>;

const Hero=({b})=>{const p=p01();return <BG><Title y={220}>{b.on_screen_text?.[0]}</Title><div style={{position:'absolute',left:170,right:170,top:560,height:520,borderRadius:44,background:C.blue,border:`14px solid ${C.yellow}`,transform:`scale(${interpolate(p,[0,1],[1,.68])})`}}/><div style={{position:'absolute',left:0,right:0,top:1210,textAlign:'center',fontSize:75,fontWeight:950,color:C.yellow,opacity:interpolate(p,[.45,.7],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'})}}>{b.on_screen_text?.[1]}</div></BG>};
const Forces=({b})=>{const p=p01();return <BG><div style={{position:'absolute',left:390,top:600,width:300,height:300,borderRadius:34,background:C.red,transform:`scale(${interpolate(p,[0,1],[1,.42])})`,display:'flex',alignItems:'center',justifyContent:'center',fontSize:44,fontWeight:900}}>NETFLIX</div>{['PRICE','MAIL','KIOSK','DIGITAL','DEBT','STORES'].map((x,i)=><Pill key={x} x={100+(i%2)*600} y={360+Math.floor(i/2)*300} w={260} label={x} color={i%2?C.blue:'#303b50'}/>)}<Title y={1450}>{b.on_screen_text?.[0]}</Title></BG>};
const Timeline=({b})=><BG light><div style={{position:'absolute',left:130,right:130,top:850,height:8,background:'#b3bac8'}}/><Pill x={170} y={730} w={220} h={220} label="2004" color={C.blue}/><Title y={1160} size={70} color="#11151f">{b.on_screen_text?.[1]}</Title></BG>;
const Dashboard=({b})=><BG><Title y={250}>BLOCKBUSTER ADAPTS</Title>{(b.on_screen_text||[]).map((x,i)=><Pill key={x} x={110+i*305} y={760} w={270} h={330} label={x} color={[C.blue,'#39445a',C.cyan][i]}/>)}</BG>;
const Journey=({b})=><BG><Title y={180}>VIEWING GETS EASIER</Title><svg width="1080" height="1200" style={{position:'absolute',top:400}}><path d="M500 950 C160 750 160 330 330 100" fill="none" stroke={C.red} strokeWidth="28" strokeDasharray="30 24"/><path d="M580 950 C850 720 880 380 760 130" fill="none" stroke={C.cyan} strokeWidth="34"/></svg><Pill x={80} y={700} label="STORE TRIP" color={C.red}/><Pill x={720} y={620} label="DVD BY MAIL" color={C.cyan}/></BG>;
const Fan=({b})=><BG>{['MAIL',...(b.on_screen_text||[])].map((x,i)=><Pill key={x} x={i%2?620:180} y={430+i*250} label={x} color={i===3?C.cyan:C.blue}/>)}</BG>;
const Reservoir=({b})=>{const p=p01();return <BG><Title y={180} size={55}>{b.on_screen_text?.[0]}</Title><div style={{position:'absolute',left:160,top:560,width:470,height:700,border:`12px solid ${C.cream}`,borderRadius:36,overflow:'hidden'}}><div style={{position:'absolute',left:0,right:0,bottom:0,height:interpolate(p,[0,1],[520,190]),background:C.blue}}/></div>{['MAIL','KIOSK','DIGITAL'].map((x,i)=><Pill key={x} x={690} y={650+i*210} w={260} label={x} color={C.cyan}/>)}</BG>};
const Bar=({b})=>{const p=p01(),v=b.data?.value||0,max=5.5;return <BG><Title y={170}>{b.on_screen_text?.[2]||'REVENUE'}</Title><div style={{position:'absolute',left:340,bottom:330,width:400,height:(v/max)*900*p,background:b.data?.previous?C.yellow:C.blue,borderRadius:'28px 28px 0 0'}}/><Title y={1320} size={88} color={b.data?.previous?C.yellow:C.cream}>{b.on_screen_text?.[0]}</Title><Title y={1440} size={56} color={C.muted}>{b.on_screen_text?.[1]}</Title></BG>};
const Stat=({b})=><BG><div style={{position:'absolute',left:170,right:170,top:560,height:610,borderRadius:75,background:C.red,display:'flex',flexDirection:'column',justifyContent:'center',alignItems:'center'}}><div style={{fontSize:80,fontWeight:950}}>{b.on_screen_text?.[0]}</div><div style={{fontSize:64,fontWeight:950,textAlign:'center',marginTop:38}}>{b.on_screen_text?.[1]}</div></div></BG>;
const Race=({b})=><BG><Title y={160}>THE INVESTMENT RACE</Title><div style={{position:'absolute',left:100,top:560,width:880,height:220,borderRadius:40,background:'#202a3b'}}/><div style={{position:'absolute',left:100,top:900,width:880,height:220,borderRadius:40,background:'#202a3b'}}/><div style={{position:'absolute',left:560,top:530,width:70,height:280,background:C.red}}/><Pill x={100} y={1280} w={390} label={b.on_screen_text?.[0]} color={C.red}/><Pill x={570} y={1280} w={410} label="CHEAPER + CONVENIENT" color={C.cyan}/></BG>;
const Legal=({b})=><BG light><div style={{position:'absolute',left:130,right:130,top:500,height:760,borderRadius:40,background:'#fff',border:'4px solid #c9c4b7',padding:70}}><div style={{fontSize:82,fontWeight:950}}>CHAPTER 11</div><div style={{fontSize:50,marginTop:35}}>BANKRUPTCY FILING</div><div style={{marginTop:170,border:`14px solid ${C.red}`,color:C.red,fontSize:62,fontWeight:950,padding:35,transform:'rotate(-8deg)'}}>SEPTEMBER 2010</div></div></BG>;
const Transfer=({b})=>{const p=p01();return <BG><Title y={190}>ASSET TRANSFER</Title><Pill x={110} y={720} w={280} h={350} label="BLOCKBUSTER" color={C.blue}/><Pill x={690} y={720} w={280} h={350} label="DISH" color="#39445a"/><div style={{position:'absolute',left:interpolate(p,[0,1],[190,700]),top:900,width:220,height:160,borderRadius:24,background:C.yellow,color:C.bg,fontSize:34,fontWeight:900,display:'flex',alignItems:'center',justifyContent:'center'}}>ASSETS</div><Title y={1360} size={56} color={C.red}>{b.on_screen_text?.[1]}</Title></BG>};
const Bottleneck=({b})=><BG><Title y={180} color={C.red}>{b.on_screen_text?.[0]}</Title><Pill x={90} y={690} w={330} h={190} label="COSTLY STORES"/><Pill x={660} y={690} w={330} h={190} label="DEBT" color={C.red}/><div style={{position:'absolute',left:455,top:1010,width:170,height:350,background:C.yellow,clipPath:'polygon(0 0,100% 0,72% 100%,28% 100%)'}}/><Pill x={340} y={1450} w={400} h={140} label="SLOW PIVOT" color="#39445a"/></BG>;

const Three=({b,mode})=><BG><ThreeCanvas width={1080} height={1920} camera={{fov:38,position:[0,1.7,8]}}><ambientLight intensity={1.5}/><directionalLight position={[4,7,6]} intensity={3}/>{mode==='cutaway'?<group><mesh><boxGeometry args={[5.5,3.2,.6]}/><meshStandardMaterial color="#2457ff"/></mesh>{Array.from({length:24}).map((_,i)=><mesh key={i} position={[-1.7+(i%6)*.68,-.9+Math.floor(i/6)*.58,.42]}><boxGeometry args={[.45,.7,.12]}/><meshStandardMaterial color={i%2?'#ffd84d':'#f6f3e9'}/></mesh>)}</group>:mode==='pivot'?<group><mesh><boxGeometry args={[4,.42,.45]}/><meshStandardMaterial color="#2457ff"/></mesh>{Array.from({length:10}).map((_,i)=><mesh key={i} position={[-2.3+i*.5,1,0]} rotation={[0,Math.PI/2,0]}><torusGeometry args={[.34,.11,12,24]}/><meshStandardMaterial color="#858b96"/></mesh>)}</group>:<group>{Array.from({length:8}).map((_,i)=><group key={i} position={[(i%2?1:-1)*1.8,-.2,-i*2.2]}><mesh><boxGeometry args={[2.25,2,1.6]}/><meshStandardMaterial color="#2457ff"/></mesh><mesh position={[0,.65,.84]}><boxGeometry args={[1.55,.35,.08]}/><meshStandardMaterial color="#ffd84d"/></mesh></group>)}</group>}</ThreeCanvas><Title y={1400} size={52}>{(b.on_screen_text||[]).join(' · ')}</Title></BG>;

const registry={RMT_HERO_MORPH:Hero,MC_MULTI_FORCE_COMPARE:Forces,MC_MILESTONE_TIMELINE:Timeline,RMT_CHANNEL_DASHBOARD:Dashboard,THREE_RETAIL_CUTAWAY:(p)=><Three {...p} mode="cutaway"/>,MC_CUSTOMER_JOURNEY:Journey,RMT_OPTION_FAN:Fan,MC_FLOW_RESERVOIR:Reservoir,D3_BAR_REVEAL:Bar,THREE_CONSTRAINED_PIVOT:(p)=><Three {...p} mode="pivot"/>,RMT_STAT_REVEAL:Stat,MC_CAPITAL_RACE:Race,RMT_TIMELINE_CARD:Legal,RMT_ASSET_TRANSFER:Transfer,THREE_STOREFRONT_ROW:(p)=><Three {...p} mode="stores"/>,MC_CAUSAL_BOTTLENECK:Bottleneck};

export const Scene=({scene})=><BG>{(scene.components||[]).map((b)=>{const Comp=registry[b.component_id];if(!Comp)return null;const from=Math.max(0,Math.round((b.start_sec-scene.start_sec)*30));const dur=Math.max(1,Math.round((b.end_sec-b.start_sec)*30));return <Sequence key={b.beat_id} from={from} durationInFrames={dur}><Comp b={b}/></Sequence>;})}</BG>;
